"""add_module_to_permission_and_relationships

Revision ID: 95c1ce0e60fd
Revises: 693bb22b083f
Create Date: 2026-09-27 11:54:44.176826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c1ce0e60fd'
down_revision: Union[str, Sequence[str], None] = '693bb22b083f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('module', sa.String(length=50), nullable=False))
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('permissions', 'module')
    # ### end Alembic commands ###
